services:
  postgres:
    image: postgis/postgis:17-3.5
    container_name: local-offers-postgres

    environment:
      POSTGRES_DB: local_offers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: